language: python
notifications:
  email: false
python:
- "2.7"
- "2.6"
- "3.3"
- "3.4"
install:
- if [[ $TRAVIS_PYTHON_VERSION == 2.6 ]]; then pip install ordereddict; fi
- pip install httpretty==0.8.10 requests mock moto responses
- python setup.py install
- pip freeze
script: python -W ignore setup.py test
